### ISSUE TITLE
incorrect checksum for freed object

### ISSUE THREAD

**Issue by tiero** [lorenzodisidoro/py-qrcode#1]
I have the following error

```
➜  py-qrcode git:(master) python3 py-qrcode.py            
Waiting to scan a QRCode
Python(2883,0x7fff95d65380) malloc: *** error for object 0x7f8f542ffc00: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
[1]    2883 abort      python3 py-qrcode.py
```

with the following QRCode
![2019-02-21 17 45 51](https://user-images.githubusercontent.com/3596602/53186045-8d4c5280-3600-11e9-9d5e-6bb7cb847ebb.jpg)

**Comment by lorenzodisidoro** [comment]
Using [pyzbar](https://pypi.org/project/pyzbar/) I have solved, quick and dirty

**Comment by lorenzodisidoro** [comment]
Try using the latest version https://github.com/lorenzodisidoro/py-qrcode/commit/c67a4b0a3259c57ee3b1d7a4f4fbab8efcf98781
